name: Daily Commit

on:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "rgarimella0124"
          git config user.email "garemella.ramsimran@gmail.com"

      - name: Append letter to file
        run: |
          echo "$(date): A" >> daily-log.md

      - name: Commit changes
        run: |
          git add daily-log.md
          git commit -m "chore: daily letter appended" || echo "No changes to commit"

      - name: Push changes
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/rgarimella0124/rgarimella0124.git
